#!/bin/sh
cd `dirname $0`
if [ -n "$JAVA_HOME" ]; then
	$JAVA_HOME/bin/java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n -jar ./UniLANChat.jar $*
else
	java -jar ./UniLANChat.jar $*
fi
cd $OLDPWD
